version: '3.7'

services:
  database:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waifubot
    ports:
      - 5432:5432

volumes:
  database-storage:
