name: Publish Release

on:
  push:
    tags:
      - "*.*"

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        uses: Leomotors/auto-publish-release@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          title: "Bocchi Bot"
          tag: ${{ github.ref }}

  image:
    name: Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image
        env:
          NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_GRAPHQL_ENDPOINT }}
        run: |
          docker build --build-arg NEXT_PUBLIC_GRAPHQL_ENDPOINT=$NEXT_PUBLIC_GRAPHQL_ENDPOINT . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/waifu-bot:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/waifu-bot
