name: Build Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: NO CRLF
        run: pnpm dlx crlf-phobia *

      - name: Install Dependencies
        run: pnpm install

      - name: Build everything
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
